### PR TITLE
Anthony Catalfo

### PR DESCRIPTION
**Pull request by AnthonyCatalfo**

### CODE REVIEW

**Comment by satishvattikuti** [comment]
Hello, 

You have done a great job. All your routes work fine. 

```
user.save((err, user) => {
    if (err) return res.send(err);
    res.json({
      success: 'User saved',
      user
    });
  });
```

Please make sure you send an error with an error code to the user. The error codes seem silly, but they are really important. It's your server is telling what is wrong with their request.

```
res.send(500).json({err:"could not save the error"});

```

```
1.  Describe Middleware, Sessions (as we know them in express), bcrypt and JWT.
    Middleware is some code that runs before the route; sessions is a persisted state in the request 
   object holding relevant user info; bcrypt is middleware that handles data hashing; JWT is a client-side 
   authentication token.
2.  What does bcrypt do in order to prevent attacks?
   It creates a hashing function that takes a certain amount of time to execute, using a SALT and the 
 given password to create it. Bcrypt basically makes it costly to brute force a password attack.
3.  What are the three parts of the JSON Web Token?
  JSON Web Tokens consist of three parts, which are:        
    Header
    Payload
    Signature
```

You should be able to answer these questions when asked in an interview because they will not give you a computer to code these in front of them. You should be able to communicate that you what's a middleware and so on.

Overall, you did a good job. Keep up the good work.

**Comment by mixelpixel** [comment]
@AnthonyCatalfo I am very pleased to see you have answered the questions in the readme.md file. Not only does it demonstrate your command of the material to Project Managers at Lambda School, the act of focusing your time and thinking on the questions and writing out the answers WILL solidify these concepts for your in such a way that you will be able to speak coherently when asked about them in interviews and while on the job. For that, you get a gold ⭐️ 

For putting only your name in your git commit messages, however, you get a hot steaming bag of 💩 .

# GIT COMMIT MESSAGES.
1. Let your git commit message titles _tell the story of your development process_. No one is expecting a novel, but some succinct _Hemingway-esque_ prose describing the state of your project as you construct discrete modules, function, etc. will
    - help your analytical thinking
    - let your development team quickly assess your work
    - help you find stuff you may have worked over which you might want to revisit

2. If you want to add additional comments and details, you can add a body to your commit messages.

```
Git commit TITLE less than 50 characters

Git commit BODY which can contain as much pertinent information and descriptions as you see fit. Some development teams like tons and tons of information, and depending on the scope of the commit, it may be necessary to make lots of detailed notes - especially in projects like React where there can be a vast amount of files and a complex architecture.
```

If you follow the above format, your `git log` will be easier to read, and, on GitHub in the Pull Requests, the body will be accessible by clicking on the three little dots:

screen shot 2018-02-10 at 9 06 14 pm

...such that they will reveal the BODY. This let's teammates, project leads, managers, as well as PMs Instructors, your classmates and whomever to quickly evaluate your development process; your investigation; _your thinking_ - and if need be, dive in a little deeper to see what and how you are doing. Also, this practice will really help _your thinking_ and _your recall_ after you've stepped away from a project for days or weeks or months and years.

screen shot 2018-02-10 at 9 06 32 pm

**As a very pragmatic note, committing often to your networks software revision control system let's your project leads and managers evaluate and incorporate your work without having to interrupt your flow when you are programming. It kills programmers productivity to have to stop programming and meet in person with someone to apprise them of your work.**

https://novicearshad.wordpress.com/2012/01/24/unplanned-interruptions-in-software-development/

productivity and interruptions

Lastly, come Monday, you need to work with your pair programming partner like so for “collaboration” through GitHub:

```
1. Person A forks the Lambda School repository.
2. Person A adds person B as a Collaborator.
3. Person B accepts invite.
4. Both clone person A's repository.
5. Work together, switch coding roles every half hour.
6. Upon the first switch, save all changes, commit, push to person A's repository and makes a Pull Request.
7. Push and pull changes as you switch.
8. Commit often!
9. Attend the end of day stand up meeting.
```

**Comment by mixelpixel** [comment]
As an example from this project - this is an excellent commit message history for this Authentication Sprint:

screen shot 2018-03-24 at 1 40 03 pm

**Comment by mixelpixel** [comment]
Here is another exemplary git commit message history from this Sprint:

screen shot 2018-03-25 at 3 34 02 am

**Pull request closed without merging**
